Update JenkinsFile

diff --git a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
--- a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
+++ b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
@@ -2,7 +2,7 @@ pipeline {
   agent {
     docker {
       image 'bhars77/maven-java17-docker-agent:latest'
-      args '-v /var/run/docker.sock:/var/run/docker.sock' // mount Docker socket to access the host's Docker daemon
+      args '--user root -v /var/run/docker.sock:/var/run/docker.sock' // mount Docker socket to access the host's Docker daemon
     }
   }
   stages {
@@ -52,20 +52,22 @@ pipeline {
         }
         steps {
             withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
-                sh '''                    
-                    echo "Current directory: $(pwd)"
-                    echo "Listing files:"
-                    ls -la
-                    echo "Checking if .git exists:"
-                    ls -la .git || echo ".git not found!"
-                    git config user.email "bhargav.mech12@gmail.com"
-                    git config user.name "Bhargav Killu"
-                    BUILD_NUMBER=${BUILD_NUMBER}
-                    sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
-                    git add java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
-                    git commit -m "Update deployment image to version ${BUILD_NUMBER}"
-                    git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
-                '''
+                sh '''
+                      su - jenkins -c '
+                          echo "Current directory: $(pwd)"
+                          echo "Listing files:"
+                          ls -la
+                          echo "Checking if .git exists:"
+                          ls -la .git || echo ".git not found!"
+                          git config user.email "bhargav.mech12@gmail.com"
+                          git config user.name "Bhargav Killu"
+                          BUILD_NUMBER=${BUILD_NUMBER}
+                          sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
+                          git add java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
+                          git commit -m "Update deployment image to version ${BUILD_NUMBER}"
+                          git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
+                      '
+                  '''
             }
         }
     }
